---
title: "Pushoverr Weather Forecast"
author: "Christian Kruse"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
```

# Pushoverr Weather Forecast

```{r}

if (!require(pacman)) { install.packages("pacman") }
pacman::p_load(pushoverr,
               dplyr,
               tidyr,
               lubridate,
               scales,
               httr,
               ggplot2,
               suncalc,
               glue,
               hms,
               data.table)

```


```{r warning=FALSE,message=FALSE,include=FALSE}
readRenviron(path = "Renviron.site")
OPENWEATHERMAP_APIKEY = Sys.getenv("OPENWEATHERMAP_APIKEY")
pushoverr::set_pushover_app(token = Sys.getenv("PUSHOVER_APPKEY"))
pushoverr::set_pushover_user(user = Sys.getenv("PUSHOVER_USERKEY"))

```

```{r eval=F}
pushoverr::pushover("Hello world")
```


```{r}
convert_timestamp = function(timestamp) {
  return( as.POSIXct( timestamp ,tz = "Europe/Copenhagen",origin="1970-01-01") )
}
```

```{r}
convert_dataframe_timestamps = function(df) {
  df$dt = convert_timestamp(df$dt)
  df$sunrise = convert_timestamp(df$sunrise)
  df$sunset = convert_timestamp(df$sunset)
  df$moonrise = convert_timestamp(df$moonrise)
  df$moonset = convert_timestamp(df$moonset)
  return( df )
}
```

```{r}
wind_angle_to_compass = function(angle)  {
    val = (angle + 11.25)/22.5
    arr = c("N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW")
    return( arr[(val %% 16)] )
}
```

```{r}
convert_kelvin= function(kelvin) {
  return( kelvin - 273.15 )
}
```


```{r include=TRUE}

lat = 55.771979
lon = 12.494786

res = GET(paste0("https://api.openweathermap.org/data/2.5/onecall?lat=",lat,"&lon=",lon,"&appid=",OPENWEATHERMAP_APIKEY)) # Yeah, should really hide that api key.

res_json = jsonlite::fromJSON( rawToChar( res$content ) )

res_json_current = res_json$current
res_json_daily = res_json$daily
res_json_hourly = res_json$hourly
res_json_minutely = res_json$minutely

res_json_daily = convert_dataframe_timestamps(res_json_daily)
res_json_current = convert_dataframe_timestamps(res_json_current)
res_json_hourly$dt = convert_timestamp(res_json_hourly$dt)
res_json_minutely$dt = convert_timestamp(res_json_minutely$dt)

res_json_current$temp = convert_kelvin( res_json_current$temp )
res_json_current$feels_like = convert_kelvin( res_json_current$feels_like )
res_json_current$dew_point = convert_kelvin( res_json_current$dew_point )

res_json_hourly$temp = convert_kelvin( res_json_hourly$temp )
res_json_hourly$feels_like = convert_kelvin( res_json_hourly$feels_like )
res_json_hourly$dew_point = convert_kelvin( res_json_hourly$dew_point )
```

# Openweather: Current Weather

So you don't need to look out the window. :-)

* Time: ```r res_json_current$dt ```
* Weather Description: ```r res_json_current$weather$description ```
* Temperature (C): ```r res_json_current$temp ```
* Feels Like (C): ```r res_json_current$feels_like ```
* Pressure (hPa): ```r res_json_current$pressure ```
* Humidity: ```r res_json_current$humidity ```
* Dew Point: ```r res_json_current$dew_point ```
* UVI Index: ```r res_json_current$uvi ```
* Clouds: ```r res_json_current$clouds ```
* Visibility: ```r res_json_current$visibility ```
* Wind Speed: ```r res_json_current$wind_speed ```
* Wind Degree: ```r res_json_current$wind_deg ```
* Wind Direction: ```r wind_angle_to_compass( res_json_current$wind_deg )```


# Openweather: Today Outdoors Weather

```{r}

rescale_capped = function(values,from) {
  
  if (from[2]>from[1]) {
    values = pmin(from[2],values)
    values = pmax(from[1],values)
    return( (values-from[1])/(from[2] - from[1]) * 100 )
  } else {
    values = pmin(from[1],values)
    values = pmax(from[2],values)
    #values = from[1] - values
    return( (values-from[1])/(from[2] - from[1]) * 100 )
    
  }
}

```

```{r}

df.scores = res_json_hourly %>% 
  filter(dt<=ymd_hms(paste0(Sys.Date()," 00:00:00"),tz = "Europe/Copenhagen")+days(1)) %>% 
  dplyr::mutate(dt=format(dt,"%H:%M"),
                pop=pop*100) 
# %>% 
  # dplyr::mutate(rain=.$rain$`1h`)

# df.scores$rain[is.na(df.scores$rain)] <- 0

df.scores = df.scores %>% 
  # dplyr::mutate(rain_score=rescale_capped(rain,from = c(10,0))) %>% 
  dplyr::mutate(temp_score=rescale_capped(temp,from = c(0,25))) %>% 
  dplyr::mutate(feels_like_score=rescale_capped(feels_like,from = c(0,25))) %>% 
  dplyr::mutate(humidity_score=rescale_capped(humidity,from = c(100,0))) %>% 
  dplyr::mutate(uvi_score=rescale_capped(uvi,from = c(0,6))) %>% 
  dplyr::mutate(clouds_score=rescale_capped(clouds,from = c(100,0))) %>% 
  dplyr::mutate(wind_speed_score=rescale_capped(wind_speed,from = c(10,0))) %>% 
  dplyr::mutate(wind_gust_score=rescale_capped(wind_gust,from = c(10,0))) %>% 
  dplyr::mutate(pop_score=rescale_capped(pop,from = c(100,0))) 


```

```{r}

draw_scorecard = function(factors) {
  
## First get DT and score

df.score = df.scores %>% 
  dplyr::select(dt,contains(factors),contains(paste0(factors,"_score")))

num_cols = sum(grepl("_score",colnames(df.score)))

df.score = df.score %>% 
  dplyr::mutate(score = round(100*rowSums(across(contains("_score")))/(num_cols*100))) %>% 
  dplyr::select(dt,score,contains(factors),-contains("_score"))

df.dt_score = df.score %>% 
  dplyr::select(dt,score)


# Then gather and join on score
df.score %>% 
  dplyr::select(dt,score,contains(factors)) %>% 
  gather(metric,value,score:ncol(.)) %>% 
  inner_join(df.dt_score, by = "dt") %>% 
  dplyr::mutate(metric=factor(metric,levels=c("score",factors))) %>% 
  ggplot(.,aes(x=metric,y=dt)) +
  geom_tile(aes(fill=score)) + 
  scale_fill_gradient2(low="red",mid="white",high="green",midpoint=50,limits = c(0,100)) +
  geom_text(aes(label=paste0(round(value,0))),color="black") +
  theme_bw() +
  theme(legend.position="null") +
  labs(x=NULL,
       y=NULL,
       title = paste0("Sun Forecast: ",format.Date(Sys.Date(),"%A %d. %B, %Y"))) + 
  scale_x_discrete(labels=c("score" = "Score 0-100",
                            "temp" = "Temperature (C)",
                            "uvi" = "UV Index",
                            "clouds" = "Clouds (%)",
                            "pop" = "Precipitation (%)",
                            "rain" = "Rain (mm)",
                            "wind_speed" = "Wind Speed (m/s)",
                            "wind_gust" = "Wind Gusts (m/s)"))



}

```

## Outdoor Sun

```{r}

order = c("temp","uvi","clouds","pop")
todays_forecast = draw_scorecard(order)
todays_forecast
```


```{r}

## First get DT and score

df.scores = res_json_hourly %>% 
  filter(!hour(dt) %in% c(23,seq(0,6) )) %>% 
  arrange(dt) %>% 
  dplyr::mutate(dt=factor(format(dt,"%A %H:%M"),levels=format(dt,"%A %H:%M")),
                pop=pop*100)
# %>% 
  # dplyr::mutate(rain=.$rain$`1h`)

# df.scores$rain[is.na(df.scores$rain)] <- 0

df.scores = df.scores %>% 
  # dplyr::mutate(rain_score=rescale_capped(rain,from = c(10,0))) %>% 
  dplyr::mutate(temp_score=rescale_capped(temp,from = c(0,25))) %>% 
  dplyr::mutate(feels_like_score=rescale_capped(feels_like,from = c(0,25))) %>% 
  dplyr::mutate(humidity_score=rescale_capped(humidity,from = c(100,0))) %>% 
  dplyr::mutate(uvi_score=rescale_capped(uvi,from = c(0,6))) %>% 
  dplyr::mutate(clouds_score=rescale_capped(clouds,from = c(100,0))) %>% 
  dplyr::mutate(wind_speed_score=rescale_capped(wind_speed,from = c(10,0))) %>% 
  dplyr::mutate(wind_gust_score=rescale_capped(wind_gust,from = c(10,0))) %>% 
  dplyr::mutate(pop_score=rescale_capped(pop,from = c(100,0))) 



```

```{r }

factors = c("temp","uvi","clouds","pop")
draw_scorecard(factors)

```

# SunCalc

```{r}
current_dt = as.POSIXct(format(Sys.time()),tz="CET")
current_date = as.Date(Sys.Date(),tz="CET")
dates_in_thisyear = seq.Date(from = floor_date(Sys.Date(),unit = "year"),to = ceiling_date(Sys.Date(),unit = "year"),by = "1 day")
```


```{r}
seq_next_14 = 
  seq.Date(Sys.Date()-days(1),Sys.Date()+days(14),by = "1 day")

event_order = c("dawn", 
                "sunrise", 
                "sunriseEnd",
                "goldenHourEnd",
                "goldenHour",
                # "solarNoon", 
                "sunsetStart", 
                "sunset", 
                "dusk", 
                "night")
event_order.labels = c("Dawn", 
                "Sunrise", 
                "Sunrise End",
                "Morning Golden Hour Ends",
                "Evening Golden Hour Start",
                # "solarNoon", 
                "Sunset Starts", 
                "Sunset", 
                "Dusk", 
                "Night")
### Next Week
df.dates.next_week = suncalc::getSunlightTimes(date = seq_next_14,
                            lat = 55.7715024,
                            lon = 12.4932282,
                            tz = "CET",
                            keep = event_order) %>% 
  gather(EventName,EventTime,dawn:night) %>% 
  dplyr::mutate(EventName=factor(EventName,levels=event_order,labels=event_order.labels))

df.dates.next_week %>% 
  filter(date>=Sys.Date()) %>% 
  ggplot(.,aes(y=date,x=EventName)) +
  geom_tile(aes(group=EventTime,fill=EventTime),color="white") +
  geom_text(aes(label=strftime(EventTime,format = "%H:%M:%S")),color="white",size=3) +
  theme_bw() +
  theme(legend.position = "null",
        axis.text.x = element_text(angle = 45, hjust=1)) +
  labs(x=NULL,y=NULL) +
  scale_y_date(date_breaks = "1 day",date_labels = "%A %d %b")

# Next Month
```

```{r}

# Pushover
sunrise = df.dates.next_week %>% filter(EventName=="Sunrise",EventTime>=Sys.Date()) %>% filter(min(EventTime)==EventTime) %>% pull(EventTime) %>% format.Date(.,"%H:%M:%S")
sunset = df.dates.next_week %>% filter(EventName=="Sunset",EventTime>=Sys.Date()) %>% filter(min(EventTime)==EventTime) %>% pull(EventTime) %>% format.Date(.,"%H:%M:%S")
gain_sunrise = df.dates.next_week %>% 
  filter(EventName=="Sunrise") %>% 
  dplyr::mutate(change=-1*(difftime(EventTime,lag((EventTime+hours(24))),units = "secs"))) %>% 
  dplyr::mutate(change=as.numeric(change)) %>% 
  dplyr::mutate(change=sprintf("+%02d:%02d", change %% 3600 %/% 60,  change %% 60 %/% 1)) %>% 
  filter(EventTime>=Sys.Date()) %>% 
  filter(min(EventTime)==EventTime) %>% 
  pull(change)
gain_sunset = df.dates.next_week %>% 
  filter(EventName=="Sunset") %>% 
  dplyr::mutate(change=-1*(difftime(EventTime,lag((EventTime+hours(24))),units = "secs"))) %>% 
  dplyr::mutate(change=as.numeric(change)) %>% 
  dplyr::mutate(change=sprintf("+%02d:%02d", change %% 3600 %/% 60,  change %% 60 %/% 1)) %>% 
  filter(EventTime>=Sys.Date()) %>% 
  filter(min(EventTime)==EventTime) %>% 
  pull(change)

# Bike score
msg_bike = tryCatch(expr= {
  bike_score = df.scores %>%
  filter(dt=="7:00") %>%
  dplyr::select(temp,pop,
                temp_score,pop_score)
  temp_ = bike_score$temp
  pop_ = bike_score$pop
  glue("Bike: {scales::number(temp_,accuracy=0.1)} C, PoP: {pop_}%")
},error=function(e) {
  glue("Bike: N/A%")
})

msg_ = glue("Sunrise: {sunrise} ({gain_sunrise})\nSunset: {sunset} ({gain_sunset})\n{msg_bike}")

```

## Next 3 Months

```{r}

seq_next_3_months = 
  seq.Date(Sys.Date(),Sys.Date()+months(3),by = "1 day")

### Next Week
df.dates.next_3_months =
  suncalc::getSunlightTimes(date = seq_next_3_months,
                            lat = 56.1572,
                            lon = 10.2107,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  group_by(date) %>% 
  dplyr::mutate(EventTime=as.numeric(difftime(EventTime,ymd_hms(paste0(date," 00:00:00"),tz = "Europe/Copenhagen"),units = "hours")))

min_time = min(df.dates.next_3_months$EventTime,na.rm = T)
min_time = floor( min_time )

max_time = max(df.dates.next_3_months$EventTime,na.rm = T)
max_time = ceiling( max_time )

seq(min_time,max_time)

ggplot(df.dates.next_3_months,aes(x=date,y = EventTime)) +
  geom_line(aes(color=EventName)) +
  theme_bw() +
  scale_x_date(date_breaks = "7 days",date_labels = "%d %b") +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date()) + 
  scale_y_continuous(breaks = seq(min_time,max_time),labels = paste0(seq(min_time,max_time) %% 24,":00")) +
  labs(x=NULL,y=NULL)

```

## 2023

```{r eval=TRUE, include=TRUE}
### 2021 Dates
df.dates_2021 =
  suncalc::getSunlightTimes(date = dates_in_thisyear,
                            lat = lat,
                            lon = lon,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  group_by(date) %>%
  dplyr::mutate(EventTime=as.numeric(difftime(EventTime,ymd_hms(paste0(date," 00:00:00"),tz = "Europe/Copenhagen"),units = "hours")))

# min_time = min(dates_in_thisyear$EventTime,na.rm = T)
# min_time = floor( min_time )

# max_time = max(dates_in_thisyear$EventTime,na.rm = T)
# max_time = ceiling( max_time )


# ggplot(df.dates_2021,aes(x=date,y = EventTime)) +
  # scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  # geom_point(aes(color=EventName)) +
  # theme_bw()+
  # theme(legend.position = "bottom") +
  # geom_vline(xintercept = Sys.Date())  +
  # scale_y_continuous(breaks = seq(min_time,max_time),labels = paste0(seq(min_time,max_time) %% 24,":00")) +
  # labs(x=NULL,y=NULL)

```


## Change in daylight coming weeks

```{r eval=TRUE, include=TRUE}

### 2021 Dates
df.dates =
  suncalc::getSunlightTimes(date = dates_in_thisyear,
                            lat = lat,
                            lon = lon,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  filter(date>=Sys.Date()) %>% 
  filter(date<=Sys.Date()+months(1)) %>% 
  group_by(EventName) %>% 
  dplyr::mutate(StartTime=EventTime) %>% 
  dplyr::mutate(StartTime=ifelse(StartTime==min(EventTime),StartTime,NA)) %>% 
  tidyr::fill(StartTime) %>% 
  group_by(EventName) %>% 
  dplyr::mutate(StartTime=as.POSIXct(StartTime,origin="1970-01-01"),tz="CET") %>% 
  dplyr::mutate(StartTime=ymd_hms(paste0(year(EventTime),"-",month(EventTime),"-",day(EventTime)," ",hour(StartTime),":",minute(StartTime),":",second(StartTime)),tz="CET")) %>% 
  dplyr::mutate(EventTime=as.POSIXct(EventTime,tz="CET")) %>% 
dplyr::mutate(MinutesChanged=round(as.numeric(difftime(EventTime,StartTime,units="mins")),digits=2)) %>% 
  dplyr::mutate(DailyChange=MinutesChanged-lag(MinutesChanged))


ggplot(df.dates,aes(x=date,y = MinutesChanged)) +
  scale_x_date(date_breaks = "3 days",date_labels = "%a %d") +
  geom_point(aes(color=EventName)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date())  +
  labs(x=NULL,y=NULL)


ggplot(df.dates,aes(x=date,y = DailyChange)) +
  scale_x_date(date_breaks = "3 days",date_labels = "%a %d") +
  geom_line(aes(color=EventName)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date())  +
  labs(x=NULL,y=NULL)

```


# Send out

```{r}

tmp_dir = tempdir()
# ggsave(filename = paste0(tmp_dir,"/sunlight.jpg"),plot = p_comingweek,device = "jpeg")
ggsave(filename = paste0(tmp_dir,"/forecast.jpg"),plot = todays_forecast,device = "jpeg")

# pushoverr::pushover("Sunlight",attachment = paste0(tmp_dir,"/sunlight.jpg"))
pushoverr::pushover("Today's Forecast",attachment = paste0(tmp_dir,"/forecast.jpg"))
pushoverr::pushover(msg_)
```

