on:
  push:
     branches:
       - master
  schedule:
    - cron:  '45 3,14 * * *'

name: pushoverr-weather-example

jobs:
  bookdown:
    name: pushoverr
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Renviron
        run: echo $'PUSHOVER_APPKEY=${{ secrets.PUSHOVER_APPKEY }}\nPUSHOVER_USERKEY=${{ secrets.PUSHOVER_USERKEY }}' >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.21
        with:
           input_file: index.Rmd
