on:
  push:
     branches:
       - master
  schedule:
    - cron:  '1 3,13 * * *'

name: pushoverr-weather-example

jobs:
  bookdown:
    name: pushoverr
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Renviron
        run: |
          cat <<'EOF' >> Renviron.site
          PUSHOVER_APPKEY=${{ secrets.PUSHOVER_APPKEY }}
          PUSHOVER_USERKEY=${{ secrets.PUSHOVER_USERKEY }}
          OPENWEATHERMAP_APIKEY=${{ secrets.OPENWEATHERMAP_APIKEY }}
          EOF
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.21
        with:
           input_file: index.Rmd
